/* Populate database with sample data. */

INSERT INTO animals (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG, SPECIES) VALUES (1, 'Agumon', '03/02/2020', 0, true, 10.23);
INSERT INTO animals (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG, SPECIES) VALUES (2, 'Gabumon', '15/11/2018', 2, true, 8);
INSERT INTO animals (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG, SPECIES) VALUES (3, 'Pikachu', '07/01/2021', 1, false, 15.04);
INSERT INTO animals (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG, SPECIES) VALUES (4, 'Devimon', '12/05/2017', 5, true, 11);
INSERT INTO animals (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG, SPECIES) VALUES (5, 'Charmander', '2020-02-08', -11, FALSE, 0);
INSERT INTO animals (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG, SPECIES) VALUES (6, 'Plantmon', '2021-11-15', -5.7, TRUE, 2);
INSERT INTO animals (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG, SPECIES) VALUES (7, 'Squirtle', '1993-04-02', -12.13, FALSE, 3);
INSERT INTO animals (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG, SPECIES) VALUES (8, 'Angemon', '2005-06-12', -45, TRUE, 1);
INSERT INTO animals (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG, SPECIES) VALUES (9, 'Boarmon', '2005-06-07', 20.4, TRUE, 7);
INSERT INTO animals (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG, SPECIES) VALUES (10, 'Blossom', '1998-10-13', 17, TRUE, 3);
INSERT INTO animals (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG, SPECIES) VALUES (11, 'Ditto', '2022-05-14', 22, TRUE, 4);
