CREATE TABLE animals (
    ID INT PRIMARY  KEY     NOT NULL,
    NAME            TEXT    NOT NULL,
    DATE_OF_BIRTH   DATE    NOT NULL,
    ESCAPE_ATTEMPTS INT     NOT NULL,
    NEUTERED        BOOLEAN NOT NULL,
    WEIGHT_KG       DECIMAL NOT NULL
);
